pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                echo 'Compiling code'
                sh 'mvn install -DskipTests -f java-demo-app/pom.xml'
            }
        }
        stage('UnitTest') {
            steps {
                echo 'Unit test'
                sh 'mvn test -f java-demo-app/pom.xml'
            }
        }
            stage('SecurityScan') {
            steps {
                echo 'Scan vulnerability'
            }
        }
        stage('QualityGate') {
            steps {
                echo 'QGate'
            }
        }
        stage('BuildApp') {
            steps {
                echo 'BuildApp'
                sh 'mvn package -f java-demo-app/pom.xml'
            }
          post {
          success {
            archiveArtifacts artifacts: '*/*/*.war', followSymlinks: false, onlyIfSuccessful: true
            }
            }
        }
            stage('Build docker image')
            {
         steps {
          sh 'docker image build -t registry.local/java-app:$BUILD_NUMBER .'
          }
        }
            stage('PushImage') {
            steps {
                echo 'Push Image to registry'
            }
        }

        stage('Deploy to Stagging Env') {
            steps {
                echo "Running app on stagging env"
                sh '''
                docker stop tomcatInstanceStaging || true
                docker rm tomcatInstanceStaging || true
                docker run -itd --name tomcatInstanceStaging -p 8083:8080 registry.local/java-app:$BUILD_NUMBER
                sh '''
            }
        }
        stage('Deploy Production Environment') {
            steps {
                timeout(time:1, unit:'DAYS'){
                input message:'Approve PRODUCTION Deployment?'
                }
                echo "Running app on Prod env"
                sh '''
                docker stop tomcatInstanceProd || true
                docker rm tomcatInstanceProd || true
                docker run -itd --name tomcatInstanceProd -p 8084:8080 registry.local/java-app:$BUILD_NUMBER
                '''
            }
        }
    }
    post { 
                always { 
                    echo 'We are in post-always'
                }
                success { 
                                mail bcc: '', body: """Hi Team,

Build #$BUILD_NUMBER is successful, please go through the url

$BUILD_URL

and verify the details.

Regards,
DevOps Team""", cc: '', from: '', replyTo: '', subject: 'BUILD SUCCESS NOTIFICATION', to: 'devopsuryaraj@gmail.com'
                }
                failure { 
            mail bcc: '', body: """Hi Team,
            
Build #$BUILD_NUMBER is unsuccessful, please go through the url

$BUILD_URL

and verify the details.

Regards,
DevOps Team""", cc: '', from: '', replyTo: '', subject: 'BUILD FAILED NOTIFICATION', to: 'devopsuryaraj@gmail.com'
                }

    }
}

