pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                echo 'Compiling code'
                sh 'mvn install -DskipTests -f java-demo-app/pom.xml'
            }
        }
        stage('UnitTest') {
            steps {
                echo 'Unit test'
                sh 'mvn test -f java-demo-app/pom.xml'
            }
        }
            stage('SecurityScan') {
            steps {
                echo 'Scan vulnerability'
            }
        }
        stage('QualityGate') {
            steps {
                echo 'QGate'
            }
        }
        stage('BuildApp') {
            steps {
                echo 'BuildApp'
                sh 'mvn package -f java-demo-app/pom.xml'
            }
        }
            stage('PushImage') {
            steps {
                echo 'Push Image to registry'
            }
        }
    }
}

